baseURL = "http://www.squad.games/"
languageCode = "en-us"
title = "Squad Games"
theme = "squadtheme"

[Params]
homepageContentTypes = ["posts"]
gaTrackingID = "G-XR0H9BG68E"

[markup.goldmark.renderer]
unsafe = true
