baseURL = "http://www.squad.games/"
languageCode = "en-us"
title = "Squad Games"
theme = "squadtheme"

[Params]
homepageContentTypes = ["posts"]
gaTrackingID = "255778585"

[markup.goldmark.renderer]
unsafe = true
